// flow-typed signature: 25ae211863410963f57fc27dc8f94277
// flow-typed version: <<STUB>>/iscroll_v5.2.x/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iscroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iscroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'iscroll/build' {
  declare module.exports: any;
}

declare module 'iscroll/build/iscroll-infinite' {
  declare module.exports: any;
}

declare module 'iscroll/build/iscroll-lite' {
  declare module.exports: any;
}

declare module 'iscroll/build/iscroll-probe' {
  declare module.exports: any;
}

declare module 'iscroll/build/iscroll-zoom' {
  declare module.exports: any;
}

declare module 'iscroll/build/iscroll' {
  declare module.exports: any;
}

declare module 'iscroll/src/close' {
  declare module.exports: any;
}

declare module 'iscroll/src/core' {
  declare module.exports: any;
}

declare module 'iscroll/src/default/_animate' {
  declare module.exports: any;
}

declare module 'iscroll/src/default/handleEvent' {
  declare module.exports: any;
}

declare module 'iscroll/src/indicator/_initIndicators' {
  declare module.exports: any;
}

declare module 'iscroll/src/indicator/_transitionTime' {
  declare module.exports: any;
}

declare module 'iscroll/src/indicator/_transitionTimingFunction' {
  declare module.exports: any;
}

declare module 'iscroll/src/indicator/_translate' {
  declare module.exports: any;
}

declare module 'iscroll/src/indicator/indicator' {
  declare module.exports: any;
}

declare module 'iscroll/src/infinite/infinite' {
  declare module.exports: any;
}

declare module 'iscroll/src/infinite/refresh' {
  declare module.exports: any;
}

declare module 'iscroll/src/keys/keys' {
  declare module.exports: any;
}

declare module 'iscroll/src/open' {
  declare module.exports: any;
}

declare module 'iscroll/src/probe/_animate' {
  declare module.exports: any;
}

declare module 'iscroll/src/probe/_move' {
  declare module.exports: any;
}

declare module 'iscroll/src/probe/indicator._move' {
  declare module.exports: any;
}

declare module 'iscroll/src/probe/probe' {
  declare module.exports: any;
}

declare module 'iscroll/src/snap/_end' {
  declare module.exports: any;
}

declare module 'iscroll/src/snap/refresh' {
  declare module.exports: any;
}

declare module 'iscroll/src/snap/snap' {
  declare module.exports: any;
}

declare module 'iscroll/src/utils' {
  declare module.exports: any;
}

declare module 'iscroll/src/wheel/wheel' {
  declare module.exports: any;
}

declare module 'iscroll/src/zoom/handleEvent' {
  declare module.exports: any;
}

declare module 'iscroll/src/zoom/refresh' {
  declare module.exports: any;
}

declare module 'iscroll/src/zoom/zoom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'iscroll/build.js' {
  declare module.exports: $Exports<'iscroll/build'>;
}
declare module 'iscroll/build/iscroll-infinite.js' {
  declare module.exports: $Exports<'iscroll/build/iscroll-infinite'>;
}
declare module 'iscroll/build/iscroll-lite.js' {
  declare module.exports: $Exports<'iscroll/build/iscroll-lite'>;
}
declare module 'iscroll/build/iscroll-probe.js' {
  declare module.exports: $Exports<'iscroll/build/iscroll-probe'>;
}
declare module 'iscroll/build/iscroll-zoom.js' {
  declare module.exports: $Exports<'iscroll/build/iscroll-zoom'>;
}
declare module 'iscroll/build/iscroll.js' {
  declare module.exports: $Exports<'iscroll/build/iscroll'>;
}
declare module 'iscroll/src/close.js' {
  declare module.exports: $Exports<'iscroll/src/close'>;
}
declare module 'iscroll/src/core.js' {
  declare module.exports: $Exports<'iscroll/src/core'>;
}
declare module 'iscroll/src/default/_animate.js' {
  declare module.exports: $Exports<'iscroll/src/default/_animate'>;
}
declare module 'iscroll/src/default/handleEvent.js' {
  declare module.exports: $Exports<'iscroll/src/default/handleEvent'>;
}
declare module 'iscroll/src/indicator/_initIndicators.js' {
  declare module.exports: $Exports<'iscroll/src/indicator/_initIndicators'>;
}
declare module 'iscroll/src/indicator/_transitionTime.js' {
  declare module.exports: $Exports<'iscroll/src/indicator/_transitionTime'>;
}
declare module 'iscroll/src/indicator/_transitionTimingFunction.js' {
  declare module.exports: $Exports<'iscroll/src/indicator/_transitionTimingFunction'>;
}
declare module 'iscroll/src/indicator/_translate.js' {
  declare module.exports: $Exports<'iscroll/src/indicator/_translate'>;
}
declare module 'iscroll/src/indicator/indicator.js' {
  declare module.exports: $Exports<'iscroll/src/indicator/indicator'>;
}
declare module 'iscroll/src/infinite/infinite.js' {
  declare module.exports: $Exports<'iscroll/src/infinite/infinite'>;
}
declare module 'iscroll/src/infinite/refresh.js' {
  declare module.exports: $Exports<'iscroll/src/infinite/refresh'>;
}
declare module 'iscroll/src/keys/keys.js' {
  declare module.exports: $Exports<'iscroll/src/keys/keys'>;
}
declare module 'iscroll/src/open.js' {
  declare module.exports: $Exports<'iscroll/src/open'>;
}
declare module 'iscroll/src/probe/_animate.js' {
  declare module.exports: $Exports<'iscroll/src/probe/_animate'>;
}
declare module 'iscroll/src/probe/_move.js' {
  declare module.exports: $Exports<'iscroll/src/probe/_move'>;
}
declare module 'iscroll/src/probe/indicator._move.js' {
  declare module.exports: $Exports<'iscroll/src/probe/indicator._move'>;
}
declare module 'iscroll/src/probe/probe.js' {
  declare module.exports: $Exports<'iscroll/src/probe/probe'>;
}
declare module 'iscroll/src/snap/_end.js' {
  declare module.exports: $Exports<'iscroll/src/snap/_end'>;
}
declare module 'iscroll/src/snap/refresh.js' {
  declare module.exports: $Exports<'iscroll/src/snap/refresh'>;
}
declare module 'iscroll/src/snap/snap.js' {
  declare module.exports: $Exports<'iscroll/src/snap/snap'>;
}
declare module 'iscroll/src/utils.js' {
  declare module.exports: $Exports<'iscroll/src/utils'>;
}
declare module 'iscroll/src/wheel/wheel.js' {
  declare module.exports: $Exports<'iscroll/src/wheel/wheel'>;
}
declare module 'iscroll/src/zoom/handleEvent.js' {
  declare module.exports: $Exports<'iscroll/src/zoom/handleEvent'>;
}
declare module 'iscroll/src/zoom/refresh.js' {
  declare module.exports: $Exports<'iscroll/src/zoom/refresh'>;
}
declare module 'iscroll/src/zoom/zoom.js' {
  declare module.exports: $Exports<'iscroll/src/zoom/zoom'>;
}
