// flow-typed signature: a6beda7938ca6639114ba4cddebecf1b
// flow-typed version: <<STUB>>/objectFitPolyfill_v2.x.x/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'objectFitPolyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'objectFitPolyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'objectFitPolyfill/dist/objectFitPolyfill.basic.min' {
  declare module.exports: any;
}

declare module 'objectFitPolyfill/dist/objectFitPolyfill.min' {
  declare module.exports: any;
}

declare module 'objectFitPolyfill/gulpfile' {
  declare module.exports: any;
}

declare module 'objectFitPolyfill/src/objectFitPolyfill.basic' {
  declare module.exports: any;
}

declare module 'objectFitPolyfill/src/objectFitPolyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'objectFitPolyfill/dist/objectFitPolyfill.basic.min.js' {
  declare module.exports: $Exports<'objectFitPolyfill/dist/objectFitPolyfill.basic.min'>;
}
declare module 'objectFitPolyfill/dist/objectFitPolyfill.min.js' {
  declare module.exports: $Exports<'objectFitPolyfill/dist/objectFitPolyfill.min'>;
}
declare module 'objectFitPolyfill/gulpfile.js' {
  declare module.exports: $Exports<'objectFitPolyfill/gulpfile'>;
}
declare module 'objectFitPolyfill/src/objectFitPolyfill.basic.js' {
  declare module.exports: $Exports<'objectFitPolyfill/src/objectFitPolyfill.basic'>;
}
declare module 'objectFitPolyfill/src/objectFitPolyfill.js' {
  declare module.exports: $Exports<'objectFitPolyfill/src/objectFitPolyfill'>;
}
