// flow-typed signature: a9924569f592afc63aa84079a5416b5d
// flow-typed version: <<STUB>>/react-preloaded_v^1.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-preloaded'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-preloaded' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-preloaded/dist/examples' {
  declare module.exports: any;
}

declare module 'react-preloaded/dist/react-preload' {
  declare module.exports: any;
}

declare module 'react-preloaded/dist/react-preloaded' {
  declare module.exports: any;
}

declare module 'react-preloaded/examples/src/ExamplePlayer' {
  declare module.exports: any;
}

declare module 'react-preloaded/examples/src/Examples' {
  declare module.exports: any;
}

declare module 'react-preloaded/examples/src/index' {
  declare module.exports: any;
}

declare module 'react-preloaded/examples/src/Spinner' {
  declare module.exports: any;
}

declare module 'react-preloaded/lib/ImageCache' {
  declare module.exports: any;
}

declare module 'react-preloaded/lib/ImageHelper' {
  declare module.exports: any;
}

declare module 'react-preloaded/lib/index' {
  declare module.exports: any;
}

declare module 'react-preloaded/lib/Preload' {
  declare module.exports: any;
}

declare module 'react-preloaded/modules/ImageCache' {
  declare module.exports: any;
}

declare module 'react-preloaded/modules/ImageHelper' {
  declare module.exports: any;
}

declare module 'react-preloaded/modules/index' {
  declare module.exports: any;
}

declare module 'react-preloaded/modules/Preload' {
  declare module.exports: any;
}

declare module 'react-preloaded/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-preloaded/dist/examples.js' {
  declare module.exports: $Exports<'react-preloaded/dist/examples'>;
}
declare module 'react-preloaded/dist/react-preload.js' {
  declare module.exports: $Exports<'react-preloaded/dist/react-preload'>;
}
declare module 'react-preloaded/dist/react-preloaded.js' {
  declare module.exports: $Exports<'react-preloaded/dist/react-preloaded'>;
}
declare module 'react-preloaded/examples/src/ExamplePlayer.js' {
  declare module.exports: $Exports<'react-preloaded/examples/src/ExamplePlayer'>;
}
declare module 'react-preloaded/examples/src/Examples.js' {
  declare module.exports: $Exports<'react-preloaded/examples/src/Examples'>;
}
declare module 'react-preloaded/examples/src/index.js' {
  declare module.exports: $Exports<'react-preloaded/examples/src/index'>;
}
declare module 'react-preloaded/examples/src/Spinner.js' {
  declare module.exports: $Exports<'react-preloaded/examples/src/Spinner'>;
}
declare module 'react-preloaded/lib/ImageCache.js' {
  declare module.exports: $Exports<'react-preloaded/lib/ImageCache'>;
}
declare module 'react-preloaded/lib/ImageHelper.js' {
  declare module.exports: $Exports<'react-preloaded/lib/ImageHelper'>;
}
declare module 'react-preloaded/lib/index.js' {
  declare module.exports: $Exports<'react-preloaded/lib/index'>;
}
declare module 'react-preloaded/lib/Preload.js' {
  declare module.exports: $Exports<'react-preloaded/lib/Preload'>;
}
declare module 'react-preloaded/modules/ImageCache.js' {
  declare module.exports: $Exports<'react-preloaded/modules/ImageCache'>;
}
declare module 'react-preloaded/modules/ImageHelper.js' {
  declare module.exports: $Exports<'react-preloaded/modules/ImageHelper'>;
}
declare module 'react-preloaded/modules/index.js' {
  declare module.exports: $Exports<'react-preloaded/modules/index'>;
}
declare module 'react-preloaded/modules/Preload.js' {
  declare module.exports: $Exports<'react-preloaded/modules/Preload'>;
}
declare module 'react-preloaded/webpack.config.js' {
  declare module.exports: $Exports<'react-preloaded/webpack.config'>;
}
