// flow-typed signature: abcaba67fe87f3dcc7d5badcda8c942c
// flow-typed version: <<STUB>>/react-iscroll_v2.0.x/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-iscroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-iscroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-iscroll/dist/prop_types' {
  declare module.exports: any;
}

declare module 'react-iscroll/dist/react-iscroll' {
  declare module.exports: any;
}

declare module 'react-iscroll/src/prop_types' {
  declare module.exports: any;
}

declare module 'react-iscroll/src/react-iscroll' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-iscroll/dist/prop_types.js' {
  declare module.exports: $Exports<'react-iscroll/dist/prop_types'>;
}
declare module 'react-iscroll/dist/react-iscroll.js' {
  declare module.exports: $Exports<'react-iscroll/dist/react-iscroll'>;
}
declare module 'react-iscroll/src/prop_types.js' {
  declare module.exports: $Exports<'react-iscroll/src/prop_types'>;
}
declare module 'react-iscroll/src/react-iscroll.jsx' {
  declare module.exports: $Exports<'react-iscroll/src/react-iscroll'>;
}
