// flow-typed signature: e390ef7b7578ce06775bb4f7bae956e3
// flow-typed version: <<STUB>>/react-dd-menu_v2.0.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dd-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dd-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dd-menu/dist/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-dd-menu/dist/index' {
  declare module.exports: any;
}

declare module 'react-dd-menu/dist/NestedDropdownMenu' {
  declare module.exports: any;
}

declare module 'react-dd-menu/example/src/js/Example' {
  declare module.exports: any;
}

declare module 'react-dd-menu/example/src/js/index' {
  declare module.exports: any;
}

declare module 'react-dd-menu/example/src/js/Options' {
  declare module.exports: any;
}

declare module 'react-dd-menu/example/webpack.config' {
  declare module.exports: any;
}

declare module 'react-dd-menu/src/js/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-dd-menu/src/js/index' {
  declare module.exports: any;
}

declare module 'react-dd-menu/src/js/NestedDropdownMenu' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dd-menu/dist/DropdownMenu.js' {
  declare module.exports: $Exports<'react-dd-menu/dist/DropdownMenu'>;
}
declare module 'react-dd-menu/dist/index.js' {
  declare module.exports: $Exports<'react-dd-menu/dist/index'>;
}
declare module 'react-dd-menu/dist/NestedDropdownMenu.js' {
  declare module.exports: $Exports<'react-dd-menu/dist/NestedDropdownMenu'>;
}
declare module 'react-dd-menu/example/src/js/Example.jsx' {
  declare module.exports: $Exports<'react-dd-menu/example/src/js/Example'>;
}
declare module 'react-dd-menu/example/src/js/index.jsx' {
  declare module.exports: $Exports<'react-dd-menu/example/src/js/index'>;
}
declare module 'react-dd-menu/example/src/js/Options.jsx' {
  declare module.exports: $Exports<'react-dd-menu/example/src/js/Options'>;
}
declare module 'react-dd-menu/example/webpack.config.js' {
  declare module.exports: $Exports<'react-dd-menu/example/webpack.config'>;
}
declare module 'react-dd-menu/src/js/DropdownMenu.js' {
  declare module.exports: $Exports<'react-dd-menu/src/js/DropdownMenu'>;
}
declare module 'react-dd-menu/src/js/index.js' {
  declare module.exports: $Exports<'react-dd-menu/src/js/index'>;
}
declare module 'react-dd-menu/src/js/NestedDropdownMenu.js' {
  declare module.exports: $Exports<'react-dd-menu/src/js/NestedDropdownMenu'>;
}
