// flow-typed signature: eff925938bd1b7d1aaa1d3cde57971b1
// flow-typed version: <<STUB>>/skygear_v1.3.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'skygear'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'skygear' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'skygear/asset' {
  declare module.exports: any;
}

declare module 'skygear/bin' {
  declare module.exports: any;
}

declare module 'skygear/cloud' {
  declare module.exports: any;
}

declare module 'skygear/dist/bundle' {
  declare module.exports: any;
}

declare module 'skygear/dist/index' {
  declare module.exports: any;
}

declare module 'skygear/dist/skygear.min' {
  declare module.exports: any;
}

declare module 'skygear/react-native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'skygear/asset.js' {
  declare module.exports: $Exports<'skygear/asset'>;
}
declare module 'skygear/bin.js' {
  declare module.exports: $Exports<'skygear/bin'>;
}
declare module 'skygear/cloud.js' {
  declare module.exports: $Exports<'skygear/cloud'>;
}
declare module 'skygear/dist/bundle.js' {
  declare module.exports: $Exports<'skygear/dist/bundle'>;
}
declare module 'skygear/dist/index.js' {
  declare module.exports: $Exports<'skygear/dist/index'>;
}
declare module 'skygear/dist/skygear.min.js' {
  declare module.exports: $Exports<'skygear/dist/skygear.min'>;
}
declare module 'skygear/react-native.js' {
  declare module.exports: $Exports<'skygear/react-native'>;
}
