// @flow

export const ERR_NOT_AUTHENTICATED = 101;
export const ERR_PERMISSION_DENIED = 102;
export const ERR_ACCESS_KEY_NOT_ACCEPTED = 103;
export const ERR_ACCESS_TOKEN_NOT_ACCEPTED = 104;
export const ERR_INVALID_CREDENTIALS = 105;
export const ERR_INVALID_SIGNATURE = 106;
export const ERR_BAD_REQUEST = 107;
export const ERR_INVALID_ARGUMENT = 108;
export const ERR_DUPLICATED = 109;
export const ERR_RESOURCE_NOT_FOUND = 110;
export const ERR_NOT_SUPPORTED = 111;
export const ERR_NOT_IMPLEMENTED = 112;
export const ERR_CONSTRAINT_VIOLATED = 113;
export const ERR_INCOMPATIBLE_SCHEMA = 114;
export const ERR_ATOMIC_OPERATION_FAILURE = 115;
export const ERR_PARTIAL_OPERATION_FAILURE = 116;
export const ERR_UNDEFINED_OPERATION = 117;
export const ERR_PLUGIN_UNAVAILABLE = 118;
export const ERR_PLUGIN_TIMEOUT = 119;
export const ERR_RECORD_QUERY_INVALID = 120;
export const ERR_PLUGIN_INITIALIZING = 121;
export const ERR_UNEXPECTED_ERROR = 10000;

export const ERR_STRIPE = 1000;

export const ERR_MISSING_PARTNER_CODE = 20001;
export const ERR_MISSING_EMAIL = 20002;
export const ERR_MISSING_MOBILE_NUMBER = 20003;
export const ERR_MISSING_DEFAULT_CURRENCY = 20004;
export const ERR_MISSING_COUNTRY_OF_RESIDENCE = 20005;
export const ERR_MISSING_FIRST_NAME = 20006;
export const ERR_MISSING_LAST_NAME = 20007;
export const ERR_MISSING_PASSPORT_NAME = 20008;
export const ERR_MISSING_SALUTATION = 20009;
export const ERR_INVALID_PARTNER_CODE = 20010;
export const ERR_INVALID_CURRENCY = 30000;
export const ERR_INVALID_COUNTRY_OF_RESIDENCE = 30001;
export const ERR_INVALID_SALUTATION = 30002;

export const ERR_INVALID_PROMO_CODE = 50001;
export const ERR_INVALID_RESERVATION = 50002;
export const ERR_RESERVATION_EXPIRED = 50003;
export const ERR_INVALID_CAPACITY = 50004;
export const ERR_INVALID_STRIPE_TOKEN = 50006;
export const ERR_PAYMENT = 50007;
export const ERR_ROOM_SOLD_OUT = 50009;

export const ERR_INVALID_FORM_DATA = 60001;

export const ERR_RECORD_NOT_FOUND = 70001;
